#!/usr/bin/python3
# Generated by Selenium IDE
import time
import os

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

tableau_pw = os.environ.get('tableau_key', None)
tableau_user = os.environ.get('tableau_user', None)
tableau_profile = 'https://public.tableau.com/profile/darren.fishell#!/'

urls = [
    'https://public.tableau.com/profile/darren.fishell#!/vizhome/senate-race-summary-dashboards/Senate' #Congress
    , 'https://public.tableau.com/profile/darren.fishell#!/vizhome/maine-state-legislature-finance/MaineSenate' #State Legislature
]

class TestCovidtrendsupdater():
    def __init__(self):
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument("--window-size=1920x1080")
        self.driver = webdriver.Chrome(executable_path=ChromeDriverManager().install()
                                       , options=chrome_options)

    def teardown_method(self):
        self.driver.quit()

    def test_authenticate(self):
        self.driver.get(tableau_profile)
        self.driver.set_window_size(1430, 1337)
        self.driver.find_element(By.CSS_SELECTOR, ".login-link").click()
        self.driver.find_element(By.ID, "login-email").send_keys(tableau_user)
        self.driver.find_element(By.ID, "login-password").send_keys(tableau_pw)
        self.driver.find_element(By.ID, "signin-submit").click()

    def test_covidtrendsupdater(self, url):
        self.driver.get(url)
        time.sleep(10)
        try:
            self.driver.find_element(By.CSS_SELECTOR, ".viz-refresh-extract").click()
            print(f'Initiated refresh for {url}')
        except:
            print('Refresh button not available to click.')

#Instantiate class
tester = TestCovidtrendsupdater()

#Authenticate
tester.test_authenticate()

#Loop through all URLs
for url in urls:
    tester.test_covidtrendsupdater(url)

tester.teardown_method()